name: Stock Data Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up GCP credentials
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          mkdir -p ~/.config/gcloud/
          echo "$GCP_CREDENTIALS" > ~/.config/gcloud/application_default_credentials.json

      - name: Run Pipeline
        run: python pipeline_repeat.py

      - name: Check Data Format Before Upload
        run: |
          python -c "import pandas as pd; df = pd.read_csv('path/to/your/intermediate_file.csv'); print(df['Date'].dtype); print(df['Date'].head())"

      - name: Upload to GCS
        run: python -c "from pipeline_repeat import update_gcs; update_gcs(pd.read_csv('path/to/your/intermediate_file.csv'))"