name: Deploy Pipeline  
on:  
  push:  
    branches: [main]  
jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v4  
      - name: Authenticate with Google Cloud  
        run: |  
          echo "${{ secrets.GCS_KEY }}" > key.json  
          gcloud auth activate-service-account --key-file=key.json  
          gcloud config set project your-gcp-project-id  
      - name: Deploy to Cloud Functions  
        run: |  
          gcloud functions deploy stock-pipeline --runtime python310 --trigger-http  
