name: Deploy Pipeline  
on:  
  push:  
    branches: [main]  
jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v4  
      - name: Set up Cloud SDK  
        uses: google-github-actions/setup-gcloud@v1  
        with:  
          service_account_key: ${{ secrets.GCS_KEY }}  
          project_id: python-stock-data-pipeline  
      - name: Check gcloud authentication  
        run: gcloud auth list  
      - name: Deploy to Cloud Functions  
        run: |  
          gcloud functions deploy stock-pipeline --runtime python310 --trigger-http  
